if(FALSE) { #skip these steps for now
projectFolder <- "C:\\Coursera\\GetAndClean\\Project.Wk3"
rawFiles      <- file.path(projectFolder,"UCI HAR Dataset",fsep="\\")
    #print(list.files(rawFiles))
features.txt  <- file.path(rawFiles,"features.txt",fsep="\\")
features      <- read.table(features.txt)
    #print(head(features))
activities.txt<- file.path(rawFiles,"activity_labels.txt",fsep="\\")
activities    <- read.table(activities.txt)
    print(head(activities))
subjectTrain.txt <- file.path(rawFiles,"train","subject_train.txt",fsep="\\")
subjectTrain     <- read.table(subjectTrain.txt)
    print(head(subjectTrain))
    print(dim(subjectTrain))
activityTrain.txt <- file.path(rawFiles,"train","y_train.txt",fsep="\\")
activityTrain     <- read.table(activityTrain.txt)
    print("head(activityTrain)")
    print(head(activityTrain))
    print("dim(activityTrain)")
    print(dim(activityTrain))
valuesTrain.txt <- file.path(rawFiles,"train","X_train.txt",fsep="\\")
valuesTrain     <- read.table(valuesTrain.txt)
    print("head(valuesTrain)")
    print(head(valuesTrain))
    print("dim(valuesTrain)")
    print(dim(valuesTrain))
subjectTest.txt <- file.path(rawFiles,"test","subject_test.txt",fsep="\\")
subjectTest     <- read.table(subjectTest.txt)
    print("head(subjectTest)")
    print(head(subjectTest))
    print("dim(subjectTest)")
    print(dim(subjectTest))
activityTest.txt <- file.path(rawFiles,"test","y_test.txt",fsep="\\")
activityTest     <- read.table(activityTest.txt)
    print("head(activityTest)")
    print(head(activityTest))
    print("dim(activityTest)")
    print(dim(activityTest))
valuesTest.txt <- file.path(rawFiles,"test","X_test.txt",fsep="\\")
valuesTest     <- read.table(valuesTest.txt)
    print("valuesTest[1:5,1:5]")
    print(valuesTest[1:5,1:5])
    print("dim(valuesTest)")
    print(dim(valuesTest))
        #Assign user-friendly names to columns
names(valuesTest)<-features[,2]
names(valuesTrain)<-features[,2]
    print("valuesTest[1:5,1:5]")
    print(valuesTest[1:5,1:5])
    print("valuesTrain[1:5,1:5]")
    print(valuesTrain[1:5,1:5])
        #Use rbind to combine test and train data sets
values=rbind(valuesTest,valuesTrain)
    print("dim(values)")
    print(dim(values))
subject=rbind(subjectTest,subjectTrain)
    print("dim(subject)")
    print(dim(subject))
    stopifnot(subject<=30)
    stopifnot(dim(subject)[2]!=1)
names(subject)="subject"
activity=rbind(activityTest,activityTrain)
    print("dim(activity)")
    print(dim(activity))
    stopifnot(activity<=6)
    stopifnot(dim(activity)[2]!=2)
valuesOfInterest<-values[,grepl("mean\\(\\)|std\\(\\)|meanFreq\\(\\)",features[,2])]
activityName<-merge(activity,activities,by.x=1,by.y=1)[,2]
tidy<-cbind(subject,activityName,valuesOfInterest)
}
tidy.txt <- "tidy.txt"
write.table(tidy, tidy.txt, row.name=FALSE)
#Ready with read.table("tidy.txt",header=TRUE)

